### ISSUE TITLE
Incorrect order of author names

### ISSUE THREAD

**Issue by ibnesayeed** [internetarchive/fatcat#27]
I have noticed that the order of author names is incorrect in https://fatcat.wiki/release/tcmnksnbabdfxl7fdrws6nkq4e as shown in the screenshot below. The list of contributors is in the correct order, but authors listed right below the title have the first author list as the last one.

![fatcat-authors-order](https://user-images.githubusercontent.com/65147/56400768-94b86280-6223-11e9-8596-e4973f2615b5.png)

**Comment by bnewbold** [comment]
Thanks for the report @ibnesayeed !

I noticed that earlier today but hadn't gotten around to investigating it. On your poke I found the problem and have pushed a fix; let me know if you see authors mis-ordered anywhere else!
