### ISSUE TITLE
Invalid ISSN-L in fatcat containers

### ISSUE THREAD

**Issue by bnewbold** [internetarchive/fatcat#39]
I was a bit sloppy during initial import, and have a bit over 100 journals (containers) with invalid ISSN-Ls (eg, checksums don't match). Here's a TSV file:

  https://gist.github.com/bnewbold/1767fd0e32449b3380d5de7fe39c9359

The majority of these seem to be single-character typos that have filtered through upstream sources. As an example:

<https://fatcat.wiki/container/lyfqyt3klnfsbewvhlspmxoyu4> (1761-7227, correct)
<https://fatcat.wiki/container/uynmrtrspngoxdjdihrwx3x6oi> (1761-7727, typo)

It would be great if somebody could go through this TSV, looking up titles on portal.issn.org, and adding the corrected ISSN-L if there is one. In some cases it is important to click through on ISSN records and ensure it is the ISSN-L ("Linking") that is getting added.

With this updated file we can fix the metadata in fatcat, as well as send correction notes to our upstream partners (Pubmed, Crossref, DOAJ, etc).

There is a larger set of 2000+ ISSNs which are not in the most recent issn.org ISSN-L mapping file, but the majority of these seem to either obscure corner cases (known to issn.org, but not listed publicly in portal, eg due to mis-registration) or some status issue (shows up in portal.issn.org but not ISSN-L listing file).

**Comment by miku** [comment]
I'm currently looking into this.

**Comment by bnewbold** [comment]
I've got some some other journal metadata work-in-progress:
- https://github.com/bnewbold/chocula
- https://archive.org/~bnewbold/chocula/

**Comment by bnewbold** [comment]
I updated the gist above with hand-corrected ISSN-Ls. Almost all were single-character typos, which I updated in fatcat; a handful I couldn't find actual ISSNs for and didn't have any releases, so I deleted the entiries; and two were test/dummy entities from Crossref which I kept (but marked as 'test' containers).

Closing now!
