### ISSUE TITLE
Add DOIs to ShareYourPaper link when they're available

### ISSUE THREAD

**Issue by JosephMcArthur** [internetarchive/fatcat#70]
SYP allows URLs such as `https://shareyourpaper.org/10.1126/scitranslmed.3001922` to go direct to a deposit page. Where Fatcat has them it would be cool to add those to the current link shown.

**Comment by bnewbold** [comment]
This is now implemented, here is an example save page: https://fatcat.wiki/release/hsmo6p4smrganpb3fndaj2lon4/save
